### ISSUE TITLE
Please support 5.15.14

### ISSUE THREAD

**Issue by CRC32EX** [devias-io/material-kit-react#163]
# Step to reproduce this issue
1. clone this repository
```
git clone https://github.com/devias-io/material-kit-react
```

2. update `@mui/material`
```
npm add @mui/material@5.15.14
```

3.  Run
```
npm run dev
```

# Error detail
```
MUI: Can't create `palette.paperChannel` because `palette.paper` is not one of these formats: #nnn, #nnnnnn, rgb(), rgba(), hsl(), hsla(), color().
To suppress this warning, you need to explicitly provide the `palette.paperChannel` as a string (in rgb format, for example "12 12 12") or undefined if you want to remove the channel token.
```

<b>package.json</b>
```
{
  "dependencies": {
    "@mui/material": "^5.15.14",
}
```

**Comment by acomanescu** [comment]
Thank you for reporting it, I'll try to update it soon. Meanwhile open `src/styles/theme/color-schemes.ts` file and where we define `paper` key, for both dark and light modes, add another key `paperChannel` with the value of the CSS variable used in `paper` in a hex format instead of a variable, e.g. `#ffffff`.

**Comment by acomanescu** [comment]
Fixed.
